services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: party_evaluation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres_password@postgres:5432/party_evaluation
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: